name: Get Azure VM Public IP

on:
  workflow_call:
    outputs:
      vm_ip:
        description: "Public IP of the VM"
        value: ${{ jobs.get-ip.outputs.vm_ip }}
    secrets:
      AZURE_CREDENTIALS:
        required: true
    inputs:
      environment:
        type: string
        default: dev

jobs:
  get-ip:
    runs-on: ubuntu-latest
    outputs:
      vm_ip: ${{ steps.get_vm_ip.outputs.vm_ip }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set dynamic variables
        id: vars
        run: |
          echo "resource_group=${{ inputs.environment }}-devops-week10-rg" >> $GITHUB_OUTPUT
          echo "vm_name=week10vm" >> $GITHUB_OUTPUT

      - name: Get Public IP Name
        id: get_ip_name
        run: |
          IP_NAME=$(az network public-ip list \
            --resource-group "${{ steps.vars.outputs.resource_group }}" \
            --query "[0].name" -o tsv)
          echo "ip_name=$IP_NAME" >> $GITHUB_OUTPUT

      - name: Make IP Static
        run: |
          az network public-ip update \
            --resource-group "${{ steps.vars.outputs.resource_group }}" \
            --name "${{ steps.get_ip_name.outputs.ip_name }}" \
            --allocation-method Static

      - name: Get VM Public IP
        id: get_vm_ip
        run: |
          VM_IP=$(az vm show -d \
            -g "${{ steps.vars.outputs.resource_group }}" \
            -n "${{ steps.vars.outputs.vm_name }}" \
            --query publicIps -o tsv)
          echo "vm_ip=$VM_IP" >> $GITHUB_OUTPUT
